/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inicio;

import conexiondata.CuartelData;
import entidades.Cuartel;

/**
 *
 * @author ELIANA
 */
public class CuartelVista extends javax.swing.JInternalFrame {

    /**
     * Creates new form CuartelVista
     */
    public CuartelVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcodigo = new javax.swing.JTextField();
        jnombre = new javax.swing.JTextField();
        jdireccion = new javax.swing.JTextField();
        jX = new javax.swing.JTextField();
        jY = new javax.swing.JTextField();
        jtelefono = new javax.swing.JTextField();
        jcorreo = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CUARTEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 130, -1));

        jLabel2.setText("Codigo de Cuartel");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setText("Nombre de Cuartel");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel5.setText("Coordenada X");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel6.setText("Coordenada Y");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 214, -1, 20));

        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel8.setText("Correo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));
        getContentPane().add(jcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 120, -1));
        getContentPane().add(jnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, -1));
        getContentPane().add(jdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 120, -1));
        getContentPane().add(jX, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 120, 20));
        getContentPane().add(jY, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, -1));
        getContentPane().add(jtelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 120, -1));
        getContentPane().add(jcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, -1));

        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
       CuartelData c = new CuartelData();
        c.eliminarCuartel(Integer.parseInt(jcodigo.getText()));
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
         
        int codCuartel = Integer.parseInt(jcodigo.getText());
        int coord_X = Integer.parseInt(jX.getText());
        int coord_Y = Integer.parseInt(jY.getText());
        int telefono = Integer.parseInt(jtelefono.getText());
       
        
       Cuartel c = new Cuartel( codCuartel, jnombre.getText(),jdireccion.getText(),coord_X, coord_Y,telefono,jtelefono.getText());
        CuartelData cd = new CuartelData();
        cd.modificarCuartel(c);
        
    }//GEN-LAST:event_modificarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
       
          int codCuartel = Integer.parseInt(jcodigo.getText());
        int coord_X = Integer.parseInt(jX.getText());
        int coord_Y = Integer.parseInt(jY.getText());
        int telefono = Integer.parseInt(jtelefono.getText());

        //System.out.println(fecha);
        Cuartel c = new Cuartel(codCuartel, jnombre.getText(),jdireccion.getText(),coord_X, coord_Y, telefono, jcorreo.getText() );
        CuartelData cd = new CuartelData();
        cd.guadarCuartel(c);
        
        
    }//GEN-LAST:event_agregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jX;
    private javax.swing.JTextField jY;
    private javax.swing.JTextField jcodigo;
    private javax.swing.JTextField jcorreo;
    private javax.swing.JTextField jdireccion;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jtelefono;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
